name: Run Tests

on: [pull_request]

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: changed-files
    outputs:
      modules: ${{ steps.set-changed-files-output.outputs.modules }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get all modules files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v38
        with:
          separator: ","
          dir_names: true
          files_yaml: |
            modules:
              - modules/**
              - '!modules/**/*.md'
