name: Run Tests

on: [pull_request]

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: changed-files
    outputs:
      modules: ${{ steps.set-changed-files-output.outputs.modules }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

